using BriskDesk.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BriskDesk.Data.TestDataBuilders
{
    public static class RandomTestDataGenerator
    {
        public static T TakeRandom<T>(this IEnumerable<T> list)
        {
            int rnd = StaticRandomNumberGenerator.Next(1, list.Count()) - 1;
            return list.ToList()[rnd];
        }

        public static string GetFirstName()
        {
            return _firstNames.TakeRandom();
        }

        public static string GetLastName()
        {
            return _lastNames.TakeRandom();
        }

        public static string GetCity()
        {
            return _cities.TakeRandom();
        }

        public static string GetCountry()
        {
            return _countries.TakeRandom();
        }

        public static string GetStreet()
        {
            return _streets.TakeRandom();
        }

        public static string GetAddress()
        {
            return string.Format("{0} st. {1}", _streets.TakeRandom(), StaticRandomNumberGenerator.Next(100)+1);
        }

        public static string GetCompany()
        {
            return _companies.TakeRandom();
        }
        public static string GetPhone()
        {
            return string.Format("+1 {0} {1} {2}", StaticRandomNumberGenerator.Next(100, 999),
                StaticRandomNumberGenerator.Next(100, 999), StaticRandomNumberGenerator.Next(1000, 9999));
        }

        public static string GerRandomText(int minWords, int maxWords, int minSentences, int maxSentences, int numParagraphs)
        {

            var words = new[]{"lorem", "ipsum", "dolor", "sit", "amet", "consectetuer",
                                "adipiscing", "elit", "sed", "diam", "nonummy", "nibh", "euismod",
                                "tincidunt", "ut", "laoreet", "dolore", "magna", "aliquam", "erat"};

            var rand = new Random();
            int numSentences = rand.Next(maxSentences - minSentences)
                + minSentences + 1;
            int numWords = rand.Next(maxWords - minWords) + minWords + 1;

            string result = string.Empty;

            for (int p = 0; p < numParagraphs; p++)
            {
                result += "<p>";
                for (int s = 0; s < numSentences; s++)
                {
                    for (int w = 0; w < numWords; w++)
                    {
                        if (w > 0) { result += " "; }
                        result += words[rand.Next(words.Length)];
                    }
                    result += ". ";
                }
                result += "</p>";
            }

            return result;
        }

        private static List<string> _firstNames = new List<string>()
        {
            "Sophia",
            "Emma",
            "Olivia",
            "Isabella",
            "Mia",
            "Ava",
            "Lily",
            "Zoe",
            "Emily",
            "Chloe",
            "Layla",
            "Madison",
            "Madelyn",
            "Abigail",
            "Aubrey",
            "Charlotte",
            "Amelia",
            "Ella",
            "Kaylee",
            "Avery",
            "Aaliyah",
            "Hailey",
            "Hannah",
            "Addison",
            "Riley",
            "Harper",
            "Aria",
            "Arianna",
            "Mackenzie",
            "Lila",
            "Evelyn",
            "Adalyn",
            "Grace",
            "Brooklyn",
            "Ellie",
            "Anna",
            "Kaitlyn",
            "Isabelle",
            "Sophie",
            "Scarlett",
            "Natalie",
            "Leah",
            "Sarah",
            "Nora",
            "Mila",
            "Elizabeth",
            "Lillian",
            "Kylie",
            "Audrey",
            "Lucy",
            "Maya",
            "Annabelle",
            "Makayla",
            "Gabriella",
            "Elena",
            "Victoria",
            "Claire",
            "Savannah",
            "Peyton",
            "Maria",
            "Alaina",
            "Kennedy",
            "Stella",
            "Liliana",
            "Allison",
            "Samantha",
            "Keira",
            "Alyssa",
            "Reagan",
            "Molly",
            "Alexandra",
            "Violet",
            "Charlie",
            "Julia",
            "Sadie",
            "Ruby",
            "Eva",
            "Alice",
            "Eliana",
            "Taylor",
            "Callie",
            "Penelope",
            "Camilla",
            "Bailey",
            "Kaelyn",
            "Alexis",
            "Kayla",
            "Katherine",
            "Sydney",
            "Lauren",
            "Jasmine",
            "London",
            "Bella",
            "Adeline",
            "Caroline",
            "Vivian",
            "Juliana",
            "Gianna",
            "Skyler",
            "Jordyn",
            "Jackson",
            "Aiden",
            "Liam",
            "Lucas",
            "Noah",
            "Mason",
            "Jayden",
            "Ethan",
            "Jacob",
            "Jack",
            "Caden",
            "Logan",
            "Benjamin",
            "Michael",
            "Caleb",
            "Ryan",
            "Alexander",
            "Elijah",
            "James",
            "William",
            "Oliver",
            "Connor",
            "Matthew",
            "Daniel",
            "Luke",
            "Brayden",
            "Jayce",
            "Henry",
            "Carter",
            "Dylan",
            "Gabriel",
            "Joshua",
            "Nicholas",
            "Isaac",
            "Owen",
            "Nathan",
            "Grayson",
            "Eli",
            "Landon",
            "Andrew",
            "Max",
            "Samuel",
            "Gavin",
            "Wyatt",
            "Christian",
            "Hunter",
            "Cameron",
            "Evan",
            "Charlie",
            "David",
            "Sebastian",
            "Joseph",
            "Dominic",
            "Anthony",
            "Colton",
            "John",
            "Tyler",
            "Zachary",
            "Thomas",
            "Julian",
            "Levi",
            "Adam",
            "Isaiah",
            "Alex",
            "Aaron",
            "Parker",
            "Cooper",
            "Miles",
            "Chase",
            "Muhammad",
            "Christopher",
            "Blake",
            "Austin",
            "Jordan",
            "Leo",
            "Jonathan",
            "Adrian",
            "Colin",
            "Hudson",
            "Ian",
            "Xavier",
            "Camden",
            "Tristan",
            "Carson",
            "Jason",
            "Nolan",
            "Riley",
            "Lincoln",
            "Brody",
            "Bentley",
            "Nathaniel",
            "Josiah",
            "Declan",
            "Jake",
            "Asher",
            "Jeremiah",
            "Cole",
            "Mateo",
            "Micah",
            "Elliot"
        };

        private static List<string> _lastNames = new List<string>()
        {
            "SMITH",
            "JOHNSON",
            "WILLIAMS",
            "JONES",
            "BROWN",
            "DAVIS",
            "MILLER",
            "WILSON",
            "MOORE",
            "TAYLOR",
            "ANDERSON",
            "THOMAS",
            "JACKSON",
            "WHITE",
            "HARRIS",
            "MARTIN",
            "THOMPSON",
            "GARCIA",
            "MARTINEZ",
            "ROBINSON",
            "CLARK",
            "RODRIGUEZ",
            "LEWIS",
            "LEE",
            "WALKER",
            "HALL",
            "ALLEN",
            "YOUNG",
            "HERNANDEZ",
            "KING",
            "WRIGHT",
            "LOPEZ",
            "HILL",
            "SCOTT",
            "GREEN",
            "ADAMS",
            "BAKER",
            "GONZALEZ",
            "NELSON",
            "CARTER",
            "MITCHELL",
            "PEREZ",
            "ROBERTS",
            "TURNER",
            "PHILLIPS",
            "CAMPBELL",
            "PARKER",
            "EVANS",
            "EDWARDS",
            "COLLINS",
            "STEWART",
            "SANCHEZ",
            "MORRIS",
            "ROGERS",
            "REED",
            "COOK",
            "MORGAN",
            "BELL",
            "MURPHY",
            "BAILEY",
            "RIVERA",
            "COOPER",
            "RICHARDSON",
            "COX",
            "HOWARD",
            "WARD",
            "TORRES",
            "PETERSON",
            "GRAY",
            "RAMIREZ",
            "JAMES",
            "WATSON",
            "BROOKS",
            "KELLY",
            "SANDERS",
            "PRICE",
            "BENNETT",
            "WOOD",
            "BARNES",
            "ROSS",
            "HENDERSON",
            "COLEMAN",
            "JENKINS",
            "PERRY",
            "POWELL",
            "LONG",
            "PATTERSON",
            "HUGHES",
            "FLORES",
            "WASHINGTON",
            "BUTLER",
            "SIMMONS",
            "FOSTER",
            "GONZALES",
            "BRYANT",
            "ALEXANDER",
            "RUSSELL",
            "GRIFFIN",
            "DIAZ",
            "HAYES"
        };

        private static List<string> _cities = new List<string>()
        {
            "New York",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Detroit",
            "Jacksonville",
            "Indianapolis",
            "San Francisco",
            "Columbus",
            "Austin",
            "Memphis",
            "Fort Worth",
            "Baltimore",
            "Charlotte"
        };

        private static List<string> _countries = new List<string>()
        {
            "United States"
        };

        private static List<string> _streets = new List<string>()
        {
            "Second",
            "Third",
            "First",
            "Fourth",
            "Park",
            "Fifth",
            "Main",
            "Sixth",
            "Oak",
            "Seventh",
            "Pine",
            "Maple",
            "Cedar",
            "Eighth",
            "Elm",
            "View",
            "Washington",
            "Ninth",
            "Lake",
            "Hill"
        };

        private static List<string> _companies = new List<string>()
        {
            "Abbott Laboratories",
            "AbbVie",
            "ACE Limited",
            "Accenture plc",
            "Actavis plc",
            "Adobe Systems Inc",
            "ADT Corp",
            "AES Corp",
            "Aetna Inc",
            "AFLAC Inc",
            "Affiliated Managers Group Inc",
            "Agilent Technologies Inc",
            "AGL Resources Inc.",
            "Air Products & Chemicals Inc",
            "Airgas Inc",
            "Akamai Technologies Inc",
            "Alcoa Inc",
            "Alexion Pharmaceuticals",
            "Allegheny Technologies Inc",
            "Allegion",
            "Allergan Inc",
            "Alliance Data Systems",
            "Allstate Corp",
            "Altera Corp",
            "Altria Group Inc",
            "Amazon.com Inc",
            "Ameren Corp",
            "American Electric Power",
            "American Express Co",
            "American International Group, Inc.",
            "American Tower Corp A",
            "Ameriprise Financial",
            "AmerisourceBergen Corp",
            "Ametek",
            "Amgen Inc",
            "Amphenol Corp A",
            "Anadarko Petroleum Corp",
            "Analog Devices, Inc.",
            "Aon plc",
            "Apache Corporation",
            "Apartment Investment & Mgmt",
            "Apple Inc.",
            "Applied Materials Inc",
            "Archer-Daniels-Midland Co",
            "Assurant Inc",
            "AT&T Inc",
            "Autodesk Inc",
            "Automatic Data Processing",
            "AutoNation Inc",
            "AutoZone Inc",
            "Avago Technologies",
            "AvalonBay Communities, Inc.",
            "Avery Dennison Corp",
            "Avon Products",
            "Baker Hughes Inc",
            "Ball Corp",
            "Bank of America Corp",
            "The Bank of New York Mellon Corp.",
            "Bard (C.R.) Inc.",
            "Baxter International Inc.",
            "BB&T Corporation",
            "Becton Dickinson",
            "Bed Bath & Beyond",
            "Bemis Company",
            "Berkshire Hathaway",
            "Best Buy Co. Inc.",
            "BIOGEN IDEC Inc.",
            "BlackRock",
            "Block H&R",
            "Boeing Company",
            "BorgWarner",
            "Boston Properties",
            "Boston Scientific",
            "Bristol-Myers Squibb",
            "Broadcom Corporation",
            "Brown-Forman Corporation",
            "C. H. Robinson Worldwide",
            "CA, Inc.",
            "Cablevision Systems Corp.",
            "Cabot Oil & Gas",
            "Cameron International Corp.",
            "Campbell Soup",
            "Capital One Financial",
            "Cardinal Health Inc.",
            "Carefusion",
            "Carmax Inc",
            "Carnival Corp.",
            "Caterpillar Inc.",
            "CBRE Group",
            "CBS Corp.",
            "Celgene Corp.",
            "CenterPoint Energy",
            "CenturyLink Inc",
            "Cerner",
            "CF Industries Holdings Inc",
            "Charles Schwab Corporation",
            "Chesapeake Energy",
            "Chevron Corp.",
            "Chipotle Mexican Grill",
            "Chubb Corp.",
            "CIGNA Corp.",
            "Cimarex Energy",
            "Cincinnati Financial",
            "Cintas Corporation",
            "Cisco Systems",
            "Citigroup Inc.",
            "Citrix Systems",
            "The Clorox Company",
            "CME Group Inc.",
            "CMS Energy",
            "Coach Inc.",
            "The Coca Cola Company",
            "Coca-Cola Enterprises",
            "Cognizant Technology Solutions",
            "Colgate-Palmolive",
            "Comcast Corp.",
            "Comerica Inc.",
            "Computer Sciences Corp.",
            "ConAgra Foods Inc.",
            "ConocoPhillips",
            "CONSOL Energy Inc.",
            "Consolidated Edison",
            "Constellation Brands",
            "Corning Inc.",
            "Costco Co.",
            "Covidien plc",
            "Crown Castle International Corp.",
            "CSX Corp.",
            "Cummins Inc.",
            "CVS Caremark Corp.",
            "D. R. Horton",
            "Danaher Corp.",
            "Darden Restaurants",
            "DaVita Inc.",
            "Deere & Co.",
            "Delphi Automotive",
            "Delta Air Lines",
            "Denbury Resources Inc.",
            "Dentsply International",
            "Devon Energy Corp.",
            "Diamond Offshore Drilling",
            "DirecTV",
            "Discover Financial Services",
            "Discovery Communications",
            "Discovery Communications",
            "Dollar General",
            "Dollar Tree",
            "Dominion Resources",
            "Dover Corp.",
            "Dow Chemical",
            "Dr Pepper Snapple Group",
            "DTE Energy Co.",
            "Du Pont (E.I.)",
            "Duke Energy",
            "Dun & Bradstreet",
            "E-Trade",
            "Eastman Chemical",
            "Eaton Corporation",
            "eBay Inc.",
            "Ecolab Inc.",
            "Edison Int'l",
            "Edwards Lifesciences",
            "Electronic Arts",
            "EMC Corp.",
            "Emerson Electric",
            "Ensco plc",
            "Entergy Corp.",
            "EOG Resources",
            "EQT Corporation",
            "Equifax Inc.",
            "Equity Residential",
            "Essex Property Trust Inc",
            "Estee Lauder Cos.",
            "Exelon Corp.",
            "Expedia Inc.",
            "Expeditors Int'l",
            "Express Scripts",
            "Exxon Mobil Corp.",
            "F5 Networks",
            "Facebook",
            "Family Dollar Stores",
            "Fastenal Co",
            "FedEx Corporation",
            "Fidelity National Information Services",
            "Fifth Third Bancorp",
            "First Solar Inc",
            "FirstEnergy Corp",
            "Fiserv Inc",
            "FLIR Systems",
            "Flowserve Corporation",
            "Fluor Corp.",
            "FMC Corporation",
            "FMC Technologies Inc.",
            "Ford Motor",
            "Fossil, Inc.",
            "Franklin Resources",
            "Freeport-McMoran Cp & Gld",
            "Frontier Communications",
            "GameStop Corp.",
            "Gannett Co.",
            "Gap (The)",
            "Garmin Ltd.",
            "General Dynamics",
            "General Electric",
            "General Growth Properties Inc.",
            "General Mills",
            "General Motors",
            "Genuine Parts",
            "Genworth Financial Inc.",
            "Gilead Sciences",
            "Goldman Sachs Group",
            "Goodyear Tire & Rubber",
            "Google Inc.",
            "Google Inc.",
            "Grainger (W.W.) Inc.",
            "Halliburton Co.",
            "Harley-Davidson",
            "Harman Int'l Industries",
            "Harris Corporation",
            "Hartford Financial Svc.Gp.",
            "Hasbro Inc.",
            "HCP Inc.",
            "Health Care REIT, Inc.",
            "Helmerich & Payne",
            "Hess Corporation",
            "Hewlett-Packard",
            "Home Depot",
            "Honeywell Int'l Inc.",
            "Hormel Foods Corp.",
            "Hospira Inc.",
            "Host Hotels & Resorts",
            "Hudson City Bancorp",
            "Humana Inc.",
            "Huntington Bancshares",
            "Illinois Tool Works",
            "Ingersoll-Rand PLC",
            "Integrys Energy Group Inc.",
            "Intel Corp.",
            "IntercontinentalExchange Inc.",
            "International Bus. Machines",
            "International Paper",
            "Interpublic Group",
            "Intl Flavors & Fragrances",
            "Intuit Inc.",
            "Intuitive Surgical Inc.",
            "Invesco Ltd.",
            "Iron Mountain Incorporated",
            "Jabil Circuit",
            "Jacobs Engineering Group",
            "Johnson & Johnson",
            "Johnson Controls",
            "Joy Global Inc.",
            "JPMorgan Chase & Co.",
            "Juniper Networks",
            "Kansas City Southern",
            "Kellogg Co.",
            "KeyCorp",
            "Keurig Green Mountain",
            "Kimberly-Clark",
            "Kimco Realty",
            "Kinder Morgan",
            "KLA-Tencor Corp.",
            "Kohl's Corp.",
            "Kraft Foods Group",
            "Kroger Co.",
            "L Brands Inc.",
            "L-3 Communications Holdings",
            "Laboratory Corp. of America Holding",
            "Lam Research",
            "Legg Mason",
            "Leggett & Platt",
            "Lennar Corp.",
            "Leucadia National Corp.",
            "Lilly (Eli) & Co.",
            "Lincoln National",
            "Linear Technology Corp.",
            "Lockheed Martin Corp.",
            "Loews Corp.",
            "Lorillard Inc.",
            "Lowe's Cos.",
            "LyondellBasell",
            "M&T Bank Corp.",
            "Macerich",
            "Macy's Inc.",
            "3M Company",
            "Marathon Oil Corp.",
            "Marathon Petroleum",
            "Marriott Int'l.",
            "Marsh & McLennan",
            "Masco Corp.",
            "Mastercard Inc.",
            "Mattel Inc.",
            "McCormick & Co.",
            "McDonald's Corp.",
            "McGraw Hill Financial",
            "McKesson Corp.",
            "Mead Johnson",
            "MeadWestvaco Corporation",
            "Medtronic Inc.",
            "Merck & Co.",
            "MetLife Inc.",
            "Microchip Technology",
            "Micron Technology",
            "Microsoft Corp.",
            "Mohawk Industries",
            "Molson Coors Brewing Company",
            "Mondelez International",
            "Monsanto Co.",
            "Monster Beverage",
            "Moody's Corp",
            "Morgan Stanley",
            "The Mosaic Company",
            "Motorola Solutions Inc.",
            "Murphy Oil",
            "Mylan Inc.",
            "Nabors Industries Ltd.",
            "NASDAQ OMX Group",
            "National Oilwell Varco Inc.",
            "Navient Corp",
            "NetApp",
            "Netflix Inc.",
            "Newell Rubbermaid Co.",
            "Newfield Exploration Co",
            "Newmont Mining Corp. (Hldg. Co.)",
            "News Corporation",
            "NextEra Energy",
            "Nielsen Holdings",
            "NIKE Inc.",
            "NiSource Inc.",
            "Noble Corp",
            "Noble Energy Inc",
            "Nordstrom",
            "Norfolk Southern Corp.",
            "Northern Trust Corp.",
            "Northrop Grumman Corp.",
            "Northeast Utilities",
            "NRG Energy",
            "Nucor Corp.",
            "Nvidia Corporation",
            "Michael Kors",
            "O'Reilly Automotive",
            "Occidental Petroleum",
            "Omnicom Group",
            "ONEOK",
            "Oracle Corp.",
            "Owens-Illinois Inc",
            "P G & E Corp.",
            "PACCAR Inc.",
            "Pall Corp.",
            "Parker-Hannifin",
            "Patterson Companies",
            "Paychex Inc.",
            "Peabody Energy",
            "Pentair Ltd.",
            "People's United Bank",
            "Pepco Holdings Inc.",
            "PepsiCo Inc.",
            "PerkinElmer",
            "Perrigo",
            "PetSmart, Inc.",
            "Pfizer Inc.",
            "Philip Morris International",
            "Phillips 66",
            "Pinnacle West Capital",
            "Pioneer Natural Resources",
            "Pitney-Bowes",
            "Plum Creek Timber Co.",
            "PNC Financial Services",
            "Polo Ralph Lauren Corp.",
            "PPG Industries",
            "PPL Corp.",
            "Praxair Inc.",
            "Precision Castparts",
            "Priceline.com Inc",
            "Principal Financial Group",
            "Procter & Gamble",
            "Progressive Corp.",
            "Prologis",
            "Prudential Financial",
            "Public Serv. Enterprise Inc.",
            "Public Storage",
            "Pulte Homes Inc.",
            "PVH Corp.",
            "QEP Resources",
            "Quanta Services Inc.",
            "QUALCOMM Inc.",
            "Quest Diagnostics",
            "Range Resources Corp.",
            "Raytheon Co.",
            "Red Hat Inc.",
            "Regeneron",
            "Regions Financial Corp.",
            "Republic Services Inc",
            "Reynolds American Inc.",
            "Robert Half International",
            "Rockwell Automation Inc.",
            "Rockwell Collins",
            "Roper Industries",
            "Ross Stores",
            "Rowan Cos.",
            "Ryder System",
            "Safeway Inc.",
            "Salesforce.com",
            "SanDisk Corporation",
            "SCANA Corp",
            "Schlumberger Ltd.",
            "Scripps Networks Interactive Inc.",
            "Seagate Technology",
            "Sealed Air Corp.(New)",
            "Sempra Energy",
            "Sherwin-Williams",
            "Sigma-Aldrich",
            "Simon Property Group Inc",
            "Smucker (J.M.)",
            "Snap-On Inc.",
            "Southern Co.",
            "Southwest Airlines",
            "Southwestern Energy",
            "Spectra Energy Corp.",
            "St Jude Medical",
            "Stanley Black & Decker",
            "Staples Inc.",
            "Starbucks Corp.",
            "Starwood Hotels & Resorts",
            "State Street Corp.",
            "Stericycle Inc",
            "Stryker Corp.",
            "SunTrust Banks",
            "Symantec Corp.",
            "Sysco Corp.",
            "T. Rowe Price Group",
            "Target Corp.",
            "TE Connectivity Ltd.",
            "TECO Energy",
            "Tenet Healthcare Corp.",
            "Teradata Corp.",
            "Tesoro Petroleum Co.",
            "Texas Instruments",
            "Textron Inc.",
            "The Hershey Company",
            "The Travelers Companies Inc.",
            "Thermo Fisher Scientific",
            "Tiffany & Co.",
            "Time Warner Inc.",
            "Time Warner Cable Inc.",
            "TJX Companies Inc.",
            "Torchmark Corp.",
            "Total System Services",
            "Tractor Supply Company",
            "Transocean",
            "TripAdvisor",
            "Twenty-First Century Fox",
            "Tyson Foods",
            "Tyco International",
            "U.S. Bancorp",
            "Under Armour",
            "Union Pacific",
            "United Health Group Inc.",
            "United Parcel Service",
            "Martin Marietta Materials",
            "United Technologies",
            "Unum Group",
            "Urban Outfitters",
            "V.F. Corp.",
            "Valero Energy",
            "Varian Medical Systems",
            "Ventas Inc",
            "Verisign Inc.",
            "Verizon Communications",
            "Vertex Pharmaceuticals Inc",
            "Viacom Inc.",
            "Visa Inc.",
            "Vornado Realty Trust",
            "Vulcan Materials",
            "Wal-Mart Stores",
            "Walgreen Co.",
            "The Walt Disney Company",
            "Graham Holdings Company",
            "Waste Management Inc.",
            "Waters Corporation",
            "WellPoint Inc.",
            "Wells Fargo",
            "Western Digital",
            "Western Union Co",
            "Weyerhaeuser Corp.",
            "Whirlpool Corp.",
            "Whole Foods Market",
            "Williams Cos.",
            "Windstream Communications",
            "Wisconsin Energy Corporation",
            "Wyndham Worldwide",
            "Wynn Resorts Ltd",
            "Xcel Energy Inc",
            "Xerox Corp.",
            "Xilinx Inc",
            "XL Capital",
            "Xylem Inc.",
            "Yahoo Inc.",
            "Yum! Brands Inc",
            "Zimmer Holdings",
            "Zions Bancorp",
            "Zoetis"
        };
    }
}

